name: Fetch Google Calendar Events

on:
  schedule:
    - cron: '0 */6 * * *'  # At minute 0 past every 6th hour
  workflow_dispatch:       # Allow manual trigger

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: alt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch and process Google Calendar events
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node fetch-events.js

      - name: Commit and push changes if any
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git diff --cached --quiet || git commit -m "Update events.json via GitHub Actions"
          git push https://x-access-token:${PAT_TOKEN}@github.com/CANRUG-Group/CANRUG.git HEAD:alt
